 FROM openjdk:17-jdk-alpine
 RUN mkdir workspace
 WORKDIR /workspace
 COPY . .


 COPY target/qp-assessment-0.0.1-SNAPSHOT.jar /qp-assessment.jar

 # Expose the port your application will run on (adjust if needed)
 EXPOSE 8080

 # Command to run your application
 CMD ["java", "-jar", "qp-assessment.jar"]